DELETE http://localhost:3001/api/blogs/614ca45b11d87fae5ef092aa
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlZGFiYWthIiwiaWQiOiI2MTRjYTNkMjExZDg3ZmFlNWVmMDkyYTUiLCJpYXQiOjE2MzI0ODYyMzMsImV4cCI6MTYzMjQ4OTgzM30.YzPs55TUiB7Rh80uPKbb03hemip2shk2isA5S9mk4ok